# This is used to start dependencies that are required to run the service or the integration tests locally.
# To use it, run the start-deps.sh script.
version: '3'
services:
  postgres:
    image: postgres:13.10-alpine
    environment:
      - POSTGRES_DB=award
      - POSTGRES_USER=award
      - POSTGRES_PASSWORD=award
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
